# C++ 코드 작성시 주의점

## 생성자에서 예외를 던질 상황을 만들지 말것

 어떤 객체 A의 생성자안에서 예외가 발생하면, A는 초기화되지 않는다.

 따라서, A의 소멸자는 호출되지 않고, 멤버 변수만 정리함. (Raw Pointer 사용시 메모리 누수 가능성이 있음)


- 생성자를 위한 함수 try 블록 사용할 것?
    -  catch문은 반드시 현재 익셉션을 다시 던지거나, 새 익셉션을 생성해야함
    - 함수 try 블록은 사용하지 않는 것이 좋음 (RAII 활용할것)

```cpp

MyClass::MyClass() 
try 
    : //생성자 이니셜라이저
{
    //생성자 본문
}
catch (const exception& e) 
{

}
```

## 소멸자에서 익셉션은 반드시 소멸자 안에서 처리

- 던지지 말것 
    - 소멸자는 기본적으로 noexcept 로 선언됨 => 만약 던지면 std::terminate() 호출해서 프로그램 종료


    